### ISSUE TITLE
فارسی سازی نسخه جدید

### ISSUE THREAD

**Issue by reza239** [MSavameri/Persian-Bootstrap-datepicker#1]
سلام
کارتون واقعا عالیه!
ممکنه نسخه جدید این تقویم رو فارسی سازی کنید؟
تو نسخه جدید امکانات جدیدی بهش اضافه شده.
با تشکر

**Comment by MSavameri** [comment]
سلام
حتما در اسرع وقت دیپلوی میکنم
با تشکر

**Comment by MSavameri** [comment]
سلام
در حال حاضر مشغول هستم،بمحض اتمام کار حتما رو ورژن جدید کار میکنم
با تشکر

**Comment by reza239** [comment]
خیلی ممنونم. لطف می‌کنید!
